{{- if .Values.elasticsearch.eck.enabled }}
{{- if ((.Capabilities.APIVersions.Has "elasticsearch.k8s.elastic.co/v1") | or .Values.elasticsearch.eck.ignoreMissing) -}}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "cortex.fullname" . }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
spec:
  {{- .Values.elasticsearch.eck.elasticSearchSpec | nindent 2 }}
{{- end }}
{{- end }}
