{{- if .Values.extraCortexConfigurations }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "cortex.extraconfigsecret" . | quote }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.extraCortexConfigurations }}
  {{ $k | quote }}: {{ $v | quote }}
  {{- end }}
{{- end }}
