{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "cortex.serviceAccountName" . }}-job-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-runner
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "cortex.serviceAccountName" . }}
{{- end }}
